### PR TITLE
Problem (fix #271): simulation runner on GH CI stopped working

### LINKED ISSUE #271: Problem: simulation runner on GH CI stopped working
https://github.com/crypto-com/chain-main/actions/runs/367462543

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- upgrade setup-go plugin

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`make`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Comment by yihuang** [comment]
> ❌ `/runsim` simulation test has failed 😅
> Can further check [here](https://github.com/crypto-com/chain-main/actions/runs/367744382)

I think the "/runsim" is not using the current version?

**Comment by allthatjazzleo** [comment]
> > ❌ `/runsim` simulation test has failed 😅
> > Can further check [here](https://github.com/crypto-com/chain-main/actions/runs/367744382)
> 
> I think the "/runsim" is not using the current version?

yes for comment triggered event, it will use master build workflow.
So, it should be merged first.

**Review by tomtau — APPROVED** [review]

**Pull request merged**
