### PR TITLE
Problem: not using the latest SDK pre-release

### PR DESCRIPTION
**Pull request by tomtau**
Solution: bumped the dependencies to rc6

### CODE REVIEW

**Review by yihuang — COMMENTED** [review]
the `vendorSha256` in `default.nix` also needs to be updated.

**Review by yihuang — APPROVED** [review]

**Comment by tomtau** [comment]
will reopen when this gets resolved: https://github.com/cosmos/cosmos-sdk/issues/8251 as it breaks the integration tests

**Comment by yihuang** [comment]
```diff
diff --git a/integration_tests/test_upgrade.py b/integration_tests/test_upgrade.py
index e292efa..1fe498f 100644
--- a/integration_tests/test_upgrade.py
+++ b/integration_tests/test_upgrade.py
@@ -16,6 +16,7 @@ from .utils import (
     parse_events,
     wait_for_block,
     wait_for_block_time,
+    wait_for_new_blocks,
     wait_for_port,
 )

@@ -171,6 +172,8 @@ def test_manual_upgrade(cosmovisor_cluster):
     cluster.reload_supervisor()
     time.sleep(5)  # FIXME the port seems still exists for a while after process stopped
     wait_for_port(rpc_port(cluster.config["validators"][0]["base_port"]))
+    # wait for a new block to make sure chain started up
+    wait_for_new_blocks(cluster, 1)

     target_height = cluster.block_height() + 15
     print("upgrade height", target_height)
```

**Pull request merged**
