### PR TITLE
Problem: upgrade test is not against current testnet version

### PR DESCRIPTION
**Pull request by yihuang**
Solution:
- make it more flexiable to test upgrade from any version pair,
  default to from v0.7.0-rc0 to current master

👮🏻👮🏻👮🏻 !!!! REFERENCE THE PROBLEM YOUR ARE SOLVING IN THE PR TITLE AND DESCRIBE YOUR SOLUTION HERE !!!! DO NOT FORGET !!!! 👮🏻👮🏻👮🏻

# PR Checklist:

- [ ] Have you read the [CONTRIBUTING.md](https://github.com/crypto-com/chain-main/blob/master/CONTRIBUTING.md)?
- [ ] Does your PR follow the [C4 patch requirements](https://rfc.zeromq.org/spec:42/C4/#23-patch-requirements)?
- [ ] Have you rebased your work on top of the latest master? 
- [ ] Have you checked your code compiles? (`make`)
- [ ] Have you included tests for any non-trivial functionality?
- [ ] Have you checked your code passes the unit tests? (`make test`)
- [ ] Have you checked your code formatting is correct? (`go fmt`)
- [ ] Have you checked your basic code style is fine? (`golangci-lint run`)
- [ ] If you added any dependencies, have you checked they do not contain any known vulnerabilities? (`go list -json -m all | nancy sleuth`)
- [ ] If your changes affect the client infrastructure, have you run the integration test?
- [ ] If your changes affect public APIs, does your PR follow the [C4 evolution of public contracts](https://rfc.zeromq.org/spec:42/C4/#26-evolution-of-public-contracts)?
- [ ] If your code changes public APIs, have you incremented the crate version numbers and documented your changes in the [CHANGELOG.md](https://github.com/crypto-com/chain-main/blob/master/CHANGELOG.md)?
- [ ] If you are contributing for the first time, please read the agreement in [CONTRIBUTING.md](https://github.com/crypto-com/chain-main/blob/master/CONTRIBUTING.md) now and add a comment to this pull request stating that your PR is in accordance with the [Developer's Certificate of Origin](https://github.com/crypto-com/chain-main/blob/master/CONTRIBUTING.md#developer-certificate-of-originn).

Thank you for your code, it's appreciated! :)

### CODE REVIEW

**Comment by yihuang** [comment]
the test fails unfortunately, the reason is still being investigated.

**Review by leejw51crypto — APPROVED** [review]
lgtm

**Comment by tomtau** [comment]
software upgrade test fails: https://github.com/crypto-com/chain-main/runs/1352023666#step:5:5438 ?

**Comment by yihuang** [comment]
> software upgrade test fails: https://github.com/crypto-com/chain-main/runs/1352023666#step:5:5438 ?

yes, here is the panic when new version starts up:
https://github.com/crypto-com/chain-main/runs/1352023666#step:5:1756

**Comment by tomtau** [comment]
should this be executed after we have migration tools (if we decide to support direct migration from 0.7-rc0)?

**Comment by tomtau** [comment]
as discussed on Slack, closing this for now

**Pull request closed without merging**
